name: ci Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: code checkout
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: install dependencies
      run: |
        pip install -r requirements.txt

    - name: run pipeline
      env:
            DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        dvc repro

    - name: Run model Tests
      env:
            DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        python -m unittest tests/test_model.py

    - name: login to Docker Hub
      if : success()
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      if : success()
          docker build -t {{ secrets.DOCKER_HUB_USERNAME }}/emotion02:latest .

    - name: Push Docker image
      if : success()
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/emotion02:latest



