name: ci Pipeline-01

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: code checkout
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: install dependencies
      run: |
        pip install -r requirements.txt

    - name: run pipeline
      env:
            DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        dvc repro

    - name: Run model Tests
      env:
            DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        python -m unittest tests/test_model.py

    - name: Login to AWS ECR
      run : |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws ecr ger-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418096737.dkr.ecr.us-east-1.amazonaws.com
    
    - name: Build Dicker Image
      run: |
        docker build -t shivraj-ecr .

    - name: Tag Docker Image
      run: |
        docker tag shivraj-ecr:latest 905418096737.dkr.ecr.us-east-1.amazonaws.com/shivraj-ecr:latest

    - name: Push Docker image AWS ECR 
      run : |
        docker push 905418096737.dkr.ecr.us-east-1.amazonaws.com/shivraj-ecr:latest
      



